export const BC_APP_CLIENT_ID = process.env.BC_APP_CLIENT_ID;
export const BC_APP_SECRET = process.env.BC_APP_SECRET;
export const BC_APP_CALLBACK_URL = process.env.BC_APP_CALLBACK_URL;
export const SUBSCRIPTION_METAFIELD_KEY =process.env.SUBSCRIPTION_METAFIELD_KEY;
export const SUBSCRIPTION_METAFIELD_NAMESPACE = process.env.SUBSCRIPTION_METAFIELD_NAMESPACE;
export const SUBSCRIPTION_CHANNEL_NAME = process.env.SUBSCRIPTION_CHANNEL_NAME;
